import PlayWith from '../img/projects/playwithBG.jpg';
import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import ProfilePicture from '../img/profiles/ailin.jpeg';


export const Ailin =
{
  english: {
    name: 'Ailina Ozola',
    email: 'ailuozols@gmail.com',
    from: 'Argentina',
    livingIn: 'Barcelona',
    dateOfBirth: '11/02/1998',
    linkedin: 'https://www.linkedin.com/in/ailinaozola/',
    profilePicture: ProfilePicture,
    languages: ['spanish', 'english', 'portuguese'],
    shortDescription: 'The youngest of the group with 22 years of life and the rest to code',
    longDescription: [
      'I used to cook for money but now i would code for food!',
      'In the past working at the kitchen and in customer service teached me how to be a team player, about perseverance, working under pressure and to adapt myself to different scenarios.',
      'During this long learning journey I discovered that I like both the backend and the frontend (not because the bootcamp title is fullstack developer!: P).',
      'I enjoy combining the logical part and the creative part (for which I feel that having studied art developed some knowledge about the display, the design that is carried out on the elements to improve the user experience so the product is more effective).',
      'Now for the first time i have the opportunity to work in something that I am passionate about, it makes me grow as a person, which constantly involves interesting challenges.',
    ],
    github: 'https://github.com/AlundraOz',
    technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
    personalProjects: [
      {
        projectName: 'LaVanguardia\'s game section',
        projectImage: Vanguardia,
        projectGithub: 'https://github.com/LaVanguardia',
        projectLink: '',
        projectDescription: 'Creation of a new and innovative game section for newspaper\'s users and personalizing it and integrating it into their digital plataform in order to create more engagement.',
        collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
        technologies: ['react', 'javascript', 'bootstrap'],
      },
      {
        projectName: 'PlayWith',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'https://playwith.es/',
        projectDescription: 'PlayWith it\'s a fun way to discover new music from all around the world while playing a quizz game',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: '',
    calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
  },
  spanish: {
    name: 'Ailina Ozola',
    email: 'ailuozols@gmail.com',
    from: 'Argentina',
    livingIn: 'Barcelona',
    dateOfBirth: '11/02/1998',
    linkedin: 'https://www.linkedin.com/in/ailinaozola/',
    profilePicture: ProfilePicture,
    languages: ['spanish', 'english', 'portuguese'],
    shortDescription: 'Soy una persona creativa y resiliente que encontró su pasión por aprender en el código',
    longDescription: [
      'Solía cocinar por dinero, ¡Pero ahora programaría por comida!',
      'En el pasado, trabajar en la cocina y en el servicio al cliente me enseñó cómo ser un jugador de equipo, sobre perseverancia, trabajar bajo presión y adaptarme a diferentes y muy distintos ambientes.',
      'Durante este largo viaje de aprendizaje descubrí que me gusta tanto el backend como el frontend (no porque el título del bootcamp sea fullstack developer ! :P) Disfruto combinando la parte lÛgica y la parte creativa',
      'Ahora, por primera vez, tengo la oportunidad de trabajar en algo que me apasiona y que me hace crecer como persona, lo que constantemente involucra desafíos interesantes.',
    ],
    github: 'https://github.com/AlundraOz',
    technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
    personalProjects: [
      {
        projectName: 'LaVanguardia sección de juegos',
        projectImage: Vanguardia,
        projectGithub: 'https://github.com/LaVanguardia',
        projectLink: '',
        projectDescription: 'Creación de una nueva e innovativa sección de juegos para los usuarios del periódico con el fin de personalizarlo e integrarlo y ganar más retorno',
        collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
        technologies: ['react', 'javascript', 'bootstrap'],
      },
      {
        projectName: 'PlayWith',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'https://playwith.es/',
        projectDescription: 'PlayWith es una forma divertida de descubrir nueva música de alrededor del mundo jugando.',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: '',
    calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
  },
};
