import Poblenou from '../img/projects/poblenou.jpg';
import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import Animate from '../img/projects/animateBG.jpg';
import NotAvailable from '../img/projects/notavailable.jpg';
import ProfilePicture from '../img/profiles/julie.jpeg';


export const Julie = {
  english: {
    name: 'Julie Brosse',
    email: 'juliebrosse31@hotmail.fr',
    profilePicture: ProfilePicture,
    from: 'France',
    livingIn: 'Spain',
    dateOfBirth: '16/03/1990',
    linkedin: 'https://www.linkedin.com/in/juliebrosse/',
    languages: ['spanish', 'english', 'french', 'german'],
    shortDescription: 'My name is Julie. I love enjoying every single moment by discovering, learning and sharing. My passions? Extreme sports, music, traveling, all kind of arts... and web development!',
    longDescription: [
      'Hello, my name is Julie and I am coming from Toulouse, France.',
      'My passions are extreme sports, music, traveling, all kind of arts... and web development!',
      'I have already been living in Berlin, Cologne, Paris, Bordeaux but have fallen in love with Spain and Barcelona. So I can enjoy speaking Spanish, English, German and French.',
      'Same with my work experiences: I have been working on events management, marketing, communication, education... but have fallen in love with the logic, creativity and non-stop learning that requires web development and like people working in that field.',
      'I am now living a dream, working on job and in a city I appreciate a lot and I am looking for a company and a team in which living it.',
      'Curious with a high taste for sharing times and knowledge with people, I like doing and trying many things in which to invest all my best.',
    ],
    github: 'https://github.com/JulieBrosseDev',
    technologies: ['node', 'javascript', 'react', 'css', 'html', 'ruby', 'mysql', 'git'],
    personalProjects: [
      {
        projectName: 'LaVanguardia Gaming Page',
        projectGithub: 'https://github.com/LaVanguardia/LaVanguardia-Fullstack',
        projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'Fullstack WebDevelopment project built mostly in remote : Creation of a responsive Gamification page (with the creation of 8 different Games) for LaVanguardia Newspaper. Creation of the games in order to attract a maximum of new readers and increase loyalty. integration of an iframe. Use of Javascrript, Nodejs, React, Express, Context, Hooks, SQL, CSS, html. (2 months). The last 5 months coding bootcamp project',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Vlada Masko'],
        technologies: ['node', 'javascript', 'react', 'css', 'html'],
      },
      {
        projectName: 'Animáte',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectLink: 'https://animate.cat/',
        projectImage: Animate,
        projectDescription: 'A responsive website made to display on a clear way a range of events according to what a specific user is looking for..no more no less. It is based on the Official Catalunya API with a system of filtering to allow the user to look for an event according to a date/period, a city and a certain field (sport, art, ...). It also displays all the events on a map. This website has been built in 3 weeks after the first 2 months of coding bootcamp.',
        collaborators: ['Vlada Masko', 'Alexandrina Serediuc'],
        technologies: ['node', 'javascript', 'react', 'css', 'html'],
      },
      {
        projectName: 'Wild Poblenou',
        projectGithub: 'https://github.com/JulieBrosseDev/Wild-Poblenou-Project',
        projectLink: 'https://juliebrossedev.github.io/Wild-Poblenou-Project/',
        projectImage: Poblenou,
        projectDescription: 'An informative page to present the cultural wealth of the Poblenou area (Barcelona, Spain)',
        collaborators: ['Vlada Masko', 'Rut Abelló'],
        technologies: ['javascript', 'css', 'html'],
      },
      {
        projectName: 'Tennis Partner',
        projectGithub: 'https://github.com/JulieBrosseDev/TennisPartner',
        projectLink: '',
        projectImage: NotAvailable,
        projectDescription: 'Responsive website built from scratch in 5 days. An app for tennis players. They can register, create a profile and find players to play with according to personalised filters. App built at the end of the 2 months of coding bootcamp',
        collaborators: [''],
        technologies: ['ruby', 'rails', 'javascript', 'css', 'html'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: 'mo54wUlfXT8',
    calendly: '#',
  },
  spanish: {
    name: 'Julie Brosse',
    email: 'juliebrosse31@hotmail.fr',
    profilePicture: ProfilePicture,
    from: 'France',
    livingIn: 'Spain',
    dateOfBirth: '16/03/1990',
    linkedin: 'https://www.linkedin.com/in/juliebrosse/',
    languages: ['spanish', 'english', 'french', 'german'],
    shortDescription: 'Mi nombre es Julie. Me encanta disfrutar de cualquier momento descubriendo, aprendiendo y compaartiendo. Mis pasiones? Deportes extremos, música, viajar, todo tipo de arte... y programar!',
    longDescription: [
      'Hola, mi nombre es Julie y soy de Toulouse, France.',
      'Mis pasiones son los deportes extremos, música, viajar, todo tipo de arte... y programar',
      'He estado viviendo en Berlin, Cologne, Paris, Bordeaux pero me he enamorado de España y de Barcelona. La puedo disfrutar hablando español, inglés, alemán y francés.',
      'Los mismo con mi experiencia laboral: He trabajado como manager de eventos, marketing, comunicaciones, educación... peró me enamoré de la lógica, creatividad y aprendizaje continuo que requiere la programación.',
      'Estoy viviendo un sueño ahora, trabajando en un sector y en una ciudad que aprecio mucho y buscando una empresa y equipo con el que vivirlo juntos.',
      'Curiosa y con buen gusto para compartir buenos ratos y conocimientos, me gusta hacer y probar multitud de cosas para conseguir invertir lo mejor de mi.',
    ],
    github: 'https://github.com/JulieBrosseDev',
    technologies: ['node', 'javascript', 'react', 'css', 'html', 'ruby', 'mysql', 'git'],
    personalProjects: [
      {
        projectName: 'LaVanguardia Gaming Page',
        projectGithub: 'https://github.com/LaVanguardia/LaVanguardia-Fullstack',
        projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'Proyecto Fullstack hecho (en su mayoría) en remoto: Creación de un sitio responsive con el fin de gamificar el periódico de la Vanguardia con 8 juegos distintos. Creación de juegos para atraer al máximo número de lectores e incrementar la fidelización. Juegos desarrollados en iframes dentro del periódico. Uso de Javascrript, Nodejs, React, Express, Context, Hooks, SQL, CSS, html. (2 meses). El último proyecto de un bootcamp de 5 meses',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Vlada Masko'],
        technologies: ['node', 'javascript', 'react', 'css', 'html'],
      },
      {
        projectName: 'Animáte',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectLink: 'https://animate.cat/',
        projectImage: Animate,
        projectDescription: 'Una página responsive hecha para mostrar de forma clara un rango de eventos según lo que el usuario está buscando. Está basada en la API oficial de la Generalitat de Catalunya con un sistema para filtrar los eventos según la fecha, la ciudad y el tipo de evento. También muestra todos los eventos en un mapa. Esta web se construyó en 3 semanas después de 2 meses de bootcamp.',
        collaborators: ['Vlada Masko', 'Alexandrina Serediuc'],
        technologies: ['node', 'javascript', 'react', 'css', 'html'],
      },
      {
        projectName: 'Wild Poblenou',
        projectGithub: 'https://github.com/JulieBrosseDev/Wild-Poblenou-Project',
        projectLink: 'https://juliebrossedev.github.io/Wild-Poblenou-Project/',
        projectImage: Poblenou,
        projectDescription: 'Una web informativa para mostrar la riqueza cultural del barrio de Poblenou, Barcelona.',
        collaborators: ['Vlada Masko', 'Rut Abelló'],
        technologies: ['javascript', 'css', 'html'],
      },
      {
        projectName: 'Tennis Partner',
        projectGithub: 'https://github.com/JulieBrosseDev/TennisPartner',
        projectLink: '',
        projectImage: NotAvailable,
        projectDescription: 'Página responsive creada desde 0 en 5 días. Aplicación para jugadores de tennis. Los usuarios se pueden registar, crear un perfil y encontrar jugadores con quien jugar basado en filtros de personalidad. Aplicación hecha al final de un bootcamp de 2 meses.',
        collaborators: [''],
        technologies: ['ruby', 'rails', 'javascript', 'css', 'html'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: 'mo54wUlfXT8',
    calendly: '#',
  },
};
