import Montjuic from '../img/projects/montjuicBG.jpg';
import PlayWith from '../img/projects/playwithBG.jpg';
import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import Pegatina from '../img/projects/pegatinaBG.jpg';
import ProfilePicture from '../img/profiles/lena.jpeg';


export const Lena =
{
  english: {
    name: 'Lena Kujath',
    email: 'l.kujath@gmx.de',
    from: 'Germany',
    livingIn: 'Barcelona',
    dateOfBirth: '22/03/1993',
    linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
    profilePicture: ProfilePicture,
    languages: ['german', 'english', 'spanish', 'french'],
    shortDescription: 'Curious programmer, eager to constantly learn new things and passionate about solving interesting problems creatively.',
    longDescription: [
      'Hi! I\'m Lena.',
      'A few months ago I decided that now would be the perfect time to learn, see and experience something new and unknown. So I committed into expanding my music and creative industries background and do a deep dive into the world of programming.',
      'Loving things that make your mind ache a bit when you try them the first time but do reward you later with an unique feeling of accomplishment (be it calculating a tricky musical cadence or dissolving a seemingly unsolvable bug in JavaScript), coding, something I got to know rather casually, became a new passion!',
      'Nietzsche once wrote "Ohne Musik wäre das Leben ein Irrtum." (Without music, life would be a mistake). And who am I to argue with Nietzsche himself? So now I try to always put some "allegro con brio" to my coding.',
      'I moved from southern germany to barcelona in January, after being given the opportunity to further pursue my goals with a scholarship for the Wild Code School coding bootcamp. Falling in love with this city quickly, I can\'t wait to engage myself in the vivid tech community here!',
      'I\'m at my best when I\'m part of a committed group and I I\'m excited at the results that diverse people from different backgrounds can deliver together. I love to work in environments, where people see no contradiction in working efficiently and sharing a good time and laugh together.',
      'So, if some of those variables could help filling the lines of your company code, let\'s start the conversation and have an interview, I\'m looking forward to it!',
    ],
    github: 'https://github.com/LenKuj',
    technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql', 'git'],
    personalProjects: [
      {
        projectName: 'Play with La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: '#',
        projectDescription: 'A project dedicated to increase fandom interaction for the band "La Pegatina" implementing gamification, social interaction and fun competition between users.',
        collaborators: ['Rut Abelló', 'Alexandrina Serediuc'],
        technologies: ['react', 'css'],
      },
      {
        projectName: 'Play With',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'playwith.es',
        projectDescription: 'After ~ 2 months of programming and recently being introduced to React - Gamification of music discovery.',
        collaborators: ['Ruth Abelló', 'Ailina Ozola'],
        technologies: ['react', 'css'],
      },
      {
        projectName: 'Barcelona WCS Hackaton',
        projectGithub: 'https://github.com/lenakujath/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'A 24 Hour friendly competitive Hackaton (which our team won) that took place in March, dedicated to develop a game and pass-time section for the spanish newspaper "La Vanguardia"',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'bootstrap', 'javascript'],
      },
      {
        projectName: 'Montjuic Webpage',
        projectImage: Montjuic,
        projectGithub: 'https://github.com/LenKuj/WCProject',
        projectLink: 'https://lenkuj.github.io/WCProject/',
        projectDescription: 'After two weeks of JS, HTML, CSS - A webpage dedicated to the discovery of the beautiful and culturaly interesting places of the Montjuic (Barcelona).',
        collaborators: ['Macarena Mariani', 'Binay Timilsina'],
        technologies: ['bootstrap', 'html', 'css', 'javascript'],
      },
    ],
    facebook: 'https://www.facebook.com/lena.kujath/',
    instagram: '',
    twitter: '',
    video: 'L17JptN9vs0',
    calendly: 'https://calendly.com/l-kujath',
  },
  spanish: {
    name: 'Lena Kujath',
    email: 'l.kujath@gmx.de',
    from: 'Alemania',
    livingIn: 'Barcelona',
    profilePicture: ProfilePicture,
    dateOfBirth: '22/03/1993',
    linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
    languages: ['german', 'english', 'spanish', 'french'],
    shortDescription: 'Programadora curiosa, con ganas de aprender siempre y apasionada de resolver problemas interesantes creativamente.',
    longDescription: [
      'Hola, soy Lena!',
      'Hace unos meses decidí que ahora sería el momento perfecto para aprender, ver y intentar algo nuevo y poco conocido. Entonces me comprometí a expandir mi experiencia que tenía en el campo de la música e industrias creativas y hacer un aprendizaje intensivo sobre la programación.',
      'Amando cosas que hacen que te duela un poco la cabeza cuando las pruebas por primera vez pero te recompense más tarde con una sensación de haber logrado algo bonito es único (ya sea calculando una cadencia musical complicada o disolviendo un error aparentemente insoluble en JavaScript), y asi programar, algo que llegué a saber por accidente, se convirtió en una nueva pasión.',
      'Nietzsche ha escrito "Ohne Musik wäre das Leben ein Irrtum." (La vida sin música sería un error). Bueno, quien soy yo para discutir con Nietzsche, así que trato de siempre poner algo de "allegro con brio" en mi código.',
      'En enero, me mudé del sur de alemania a Barcelona, después de tener la oportunidad de seguir mis objetivos con una beca para el bootcamp de "Wild Code School". Enamorandome de esta ciudad rápidamente, no puedo esperar para involucrarme en la vívida comunidad tecnológica aquí!',
      'Estoy en mi mejor forma cuando formo parte de un grupo comprometido y estoy entusiasmada con los resultados que diversas personas de diferentes orígenes pueden ofrecer juntas. Me encanta trabajar en entornos donde la gente no ve contradicción en trabajar eficientemente y compartir un buen momento y reír juntos.',
      'Entonces, si algunas de esas variables podrían ayudar a completar las líneas del código de su empresa, comencemos la conversación y tengamos una entrevista, me encantaria!',
    ],
    github: 'https://github.com/LenKuj',
    technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql', 'git'],
    personalProjects: [
      {
        projectName: 'Juega con La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: '#',
        projectDescription: 'Un proyecto dedicado a aumentar la interacción fandom para la banda implementando gamificación, interacción social y competencia divertida entre los usarios.',
        collaborators: ['Rut Abelló', 'Alexandrina Serediuc'],
        technologies: ['react', 'css'],
      },
      {
        projectName: 'Play With',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'playwith.es',
        projectDescription: 'Después de dos meses de aprender en Wild Code School - Te permite encontrar nueva música de todo el mundo jugando.',
        collaborators: ['Ruth Abelló', 'Ailina Ozola'],
        technologies: ['react', 'css'],
      },
      {
        projectName: 'Barcelona Hackaton',
        projectGithub: 'https://github.com/lenakujath/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'Un Hackaton competitivo amistoso de 24 horas de duración (que ganó nuestro equipo), que tuvo lugar en marzo, dedicado a desarrollar un juego y la sección de pasatiempo para el periodico español "La Vanguardia".',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'css', 'javascript', 'html'],
      },
      {
        projectName: 'Montjuic Webpage',
        projectGithub: 'https://github.com/LenKuj/WCProject',
        projectImage: Montjuic,
        projectLink: 'https://lenkuj.github.io/WCProject/',
        projectDescription: 'Después de dos semanas de aprender en Wild Code School - Una pagina web dedicada a encontrar los lugares hermoses y culturalmente interesantes de Montjuic (Barcelona).',
        collaborators: ['Macarena Mariani', 'Binay Timilsina'],
        technologies: ['bootstrap', 'html', 'css', 'javascript'],
      },
    ],
    facebook: 'https://www.facebook.com/lena.kujath/',
    instagram: '',
    twitter: '',
    video: 'L17JptN9vs0',
    calendly: 'https://calendly.com/l-kujath',
  },
};
