import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import RickAndMorty from '../img/projects/rickMortyBG.jpg';
import ProfilePicture from '../img/profiles/mireia.jpeg';


export const Mireia =
{
  english: {
    name: 'Mireia Gomariz',
    email: 'mireiapgomariz@gmail.com',
    from: 'Barcelona',
    livingIn: 'Barcelona',
    dateOfBirth: '07/08/1993',
    linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
    profilePicture: ProfilePicture,
    languages: ['spanish', 'english', 'catalan'],
    shortDescription: 'FullStack web developer with sales and sanitary background',
    longDescription: [
      'Hi! I\'m Mireia.',
      'I have 26 years old and I live in a city near to Barcelona, I have a sanitary background, studying and working as a physiotherapist but at some point I decided to move my professional career into the developing world.',
      'I had experience also in sales and administration, and this give me communication and teamwork skills.',
      'I started studying development at home by my own one and a half year ago and then I had the possibility to start a Fullstack boot camp with the aim to have intensive formation and really based to introduce our self to work in a professional way.',
      'I was obtaining great experiences in this bootcamp and also I had the possibility to work with a huge real client like La Vanguardia news paper',
    ],
    github: 'https://github.com/mireiaGomariz',
    technologies: ['react', 'node', 'javascript'],
    personalProjects: [
      {
        projectName: 'La Vanguardia game section',
        projectImage: Vanguardia,
        projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
        projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
        projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
        collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
        technologies: ['react', 'node'],
      },
      {
        projectName: 'ShowMeWhatYouGot',
        projectImage: RickAndMorty,
        projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
        projectLink: 'link to project2',
        projectDescription: 'Game web page about Rick and Morty show',
        collaborators: ['Maca Mariani'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: 'https://twitter.com/GomarizMireia',
    video: 'HTjqY0bihaU',
    calendly: 'https://calendly.com/mireiapgomariz',
  },
  spanish: {
    name: 'Mireia Gomariz',
    email: 'mireiapgomariz@gmail.com',
    from: 'Barcelona',
    livingIn: 'Barcelona',
    dateOfBirth: '07/08/1993',
    linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
    profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQEo28zXbNhgYA/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=r_Qk2pq-v8T43marFV39lhoPFc3ip_JCzkHTL3IXLwM',
    languages: ['spanish', 'english', 'catalan'],
    shortDescription: 'FullStack web developer with sales and sanitary background',
    longDescription: [
      'Hola!',
      'Soy Mireia, tengo 26 años y vivo en una ciudad cerca de Barcelona.',
      'Provengo del sector sanitario, estudié fisioterapia pero decidí hacer un cambio en mi vida y empezar a dedicarme a la programación.',
      'Tengo experiencia en ventas y administración, lo que me ayudó a desarrollar mis habilidades comunicativas y de trabajo en equipo.',
      'Empecé a estudiar programación por mi cuenta pero decidí realizar un bootcamp para tener una formación intensiva enfocada a la profesionalización.',
      'He obtenido grandes experiencias en este bootcamp y he podido trabajar en un proyecto con un cliente real como es el periódico La Vanguardia.',
    ],
    github: 'https://github.com/mireiaGomariz',
    technologies: ['react', 'node', 'javascript'],
    personalProjects: [
      {
        projectName: 'La Vanguardia game section',
        projectImage: Vanguardia,
        projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
        projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
        projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
        collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
        technologies: ['react', 'node'],
      },
      {
        projectName: 'ShowMeWhatYouGot',
        projectImage: RickAndMorty,
        projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
        projectLink: 'link to project2',
        projectDescription: 'Game web page about Rick and Morty show',
        collaborators: ['Maca Mariani'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: 'https://twitter.com/GomarizMireia',
    video: 'HTjqY0bihaU',
    calendly: 'https://calendly.com/mireiapgomariz',
  },
};
