import PlayWith from '../img/projects/playwithBG.jpg';
import Pegatina from '../img/projects/pegatinaBG.jpg';
import ProfilePicture from '../img/profiles/rut.jpeg';


export const Rut =
{
  english: {
    name: 'Ruth Abelló',
    email: 'rut.abello@gmail.com',
    from: 'Reus',
    livingIn: 'Gelida',
    dateOfBirth: '14/09/1987',
    profilePicture: ProfilePicture,
    linkedin: 'https://www.linkedin.com/in/ruth-abello-cort/',
    languages: ['catalan', 'spanish', 'english'],
    technologies: ['react', 'node', 'javascript'],
    shortDescription: 'Former journalist converted into a passionate front-end developer',
    longDescription: [
      'People keep asking me how come a journalist is now a web developer.',
      'My answer is always the same: "The true question here should be \'How come a web developer used to be a journalist?\'".',
      'Because, considering my background, my passion for everything related to science and tech, what\'s not clear at all is how I ended up in journalism school.It took me 8 years getting back again to the right path(not that journalism wasn\'t right, I also had a lot of fun and learned a lot there, but, you know...), but here I am.',
      'I\'ve cried, dealt with frustration, learned so much in such a short time, proved myself wrong, failed, and, finally, succeeded.What I like the most, the infinite amount of opportunities to keep learning and never stop doing it, because technology is in constant change, and so am I.',
    ],
    github: 'https://github.com/rutabello/',
    personalProjects: [
      {
        projectName: 'Play With La Pegatina',
        projectImage: Pegatina,
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectLink: '',
        projectDescription: 'Prove no-one knows more than you do about La Pegatina by playing with their music, videos and pictures. Make points and exchange them for concert tickets, trips, music and meet&greets',
        collaborators: ['Lena Kujath', 'Alexandrina Serediuc'],
        technologies: ['react'],
      },
      {
        projectName: 'Play With',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'https://playwith.es/',
        projectDescription: 'Play With lets you learn new worldwide music while playing with it',
        collaborators: ['Ailina Ozola', 'Lena Kujath'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: 'It8mlr2s9kI',
    calendly: 'https://calendly.com/ruthere',
  },
  spanish: {
    name: 'Ruth Abelló',
    email: 'rut.abello@gmail.com',
    from: 'Reus',
    livingIn: 'Gelida',
    dateOfBirth: '14/09/1987',
    profilePicture: ProfilePicture,
    linkedin: 'https://www.linkedin.com/in/ruth-abello-cort-/',
    languages: ['catalan', 'spanish', 'english'],
    technologies: ['react', 'node', 'javascript'],
    shortDescription: 'Periodista reconvertida en apasionada por la programación font-end',
    longDescription: [
      'La gente que me conoce no para de preguntarme qué hacía una periodista estudiando para ser programadora.',
      'Mi respuesta es siempre la misma: "La pregunta, realmente, debería ser \'Qué hacía una programadora trabajando de periodista\'".',
      'Y es que, tomando en consideración mi experiencia, mi pasión desde siempre por los números y todo lo relacionado con la ciencia y le tecnología, lo que no está nada claro es cómo acabé en la facultad de periodismo. Me llevó 8 años de ejercicio del periodismo darme cuenta que ese no era mi camino (no es que no fuera un buen camino, lo pasé muy bien y aprendí mucho, pero...) y encontrar el camino que sí era correcto para mí, pero aquí estoy.',
      'He llorado, me ha tocado lidiar con la frustración, he aprendido mucho en muy poco tiempo, me he equivocado y he aprendido de cada error. Lo que más me gusta de todo este cambio: las oportunidades infinitas que ofrece de seguir aprendiendo y nunca dejar de hacerlo, porque la tecnología está en constante cambio. Igual que yo.',
    ],
    github: 'https://github.com/rutabello/',
    personalProjects: [
      {
        projectName: 'Juega con La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: '',
        projectDescription: 'Demuestra que eres quien más sabe sobre La Pegatina mientras juegas con su música, sus fotos y sus vídeos. Gana puntos y cámbialos por entradas a conciertos, meet&greets, música y viajes!',
        collaborators: ['Lena Kujath', 'Alexandrina Serediuc'],
        technologies: ['react'],
      },
      {
        projectName: 'Play With',
        projectImage: PlayWith,
        projectGithub: 'https://github.com/rutabello/PlayWith',
        projectLink: 'https://playwith.es/',
        projectDescription: 'Play With es una herramienta que te permite descubrir nueva música de todo el mundo a medida que juegas con ella.',
        collaborators: ['Ailina Ozola', 'Lena Kujath'],
        technologies: ['react'],
      },
    ],
    facebook: '',
    instagram: '',
    twitter: '',
    video: 'It8mlr2s9kI',
    calendly: 'https://calendly.com/ruthere',
  },
};
