import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import Gracia from '../img/projects/graciaBG.jpg';
import Pegatina from '../img/projects/pegatinaBG.jpg';
import Animate from '../img/projects/animateBG.jpg';
import HolaDulce from '../img/projects/holadulce.jpg';
import ProfilePicture from '../img/profiles/sandra.jpeg';


export const Sandra =
{
  english: {
    name: 'Alexandrina Serediuc',
    email: 'alecsandra.serediuc@gmail.com',
    from: 'Republic of Moldova',
    livingIn: 'Barcelona',
    dateOfBirth: '29/04/1990',
    linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
    profilePicture: ProfilePicture,
    languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
    shortDescription: 'Creative junior developer with a strong will to learn and grow',
    longDescription: [
      'The last 5 months was the best challenge so far.',
      'Learning to code and apply it in the bootcamp projects. Besides the technical skills I\'ve learned how to deal with error/conflicts, accept critics and be a team player. I have a curious mind and a strong desire to grow, discover and solve new challenges.',
      'I have my bachelor degree in Public Administration and worked the last 5 years in the film industry.',
      'My previous experience allowed me to develop the ability to strategically plan, develop and implement projects towards the achievement of the team\'s objectives',
    ],
    github: 'https://github.com/Alecsundra',
    technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
    personalProjects: [
      {
        projectName: 'La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: '#',
        projectDescription: 'The Real Client Project. Building an engagement platform for La Pegatina fans( music band of Catalan rumba) based on games ( play with music, videos and images). Using the connection with back-end(learning it in the same time), the user can register and keep the points.',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react', 'youtube', 'node', 'mysql'],
      },
      {
        projectName: 'Hackathon-Hola Dulce',
        projectGithub: 'https://github.com/Hackaton-holadulce/Front',
        projectLink: '#',
        projectImage: HolaDulce,
        projectDescription: 'Two days remote hackathon, building an administartive page to manage the stock.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'mysql', 'node'],
      },
      {
        projectName: 'Barcelona Hackathon',
        projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'The hackathon client- La Vanguardia(spanish newspaper owned by Grupo Godó).We had to build an engagement platform, based on games during 24 hours. It was a great experience.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'bootstrap'],
      },
      {
        projectName: 'Animate',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectImage: Animate,
        projectLink: 'link to project2',
        projectDescription: 'Second Bootcamp project, made in 4 weeks. We\'ve learned and practiced in the same time React.js, using an external API and npm packages. The project come up with an online app where you can find(using a filter) events in Catalunya(using the Generalidad API) and see them on a map.',
        collaborators: ['Vlada Masko', 'Julie Brosse'],
        technologies: ['react', 'material', 'leaflet', 'css'],
      },
      {
        projectName: 'StreetsOfGracia',
        projectGithub: 'https://github.com/mireiaGomariz/project1',
        projectImage: Gracia,
        projectLink: 'https://mireiagomariz.github.io/project1/index.html',
        projectDescription: 'First week bootcamp project. Great way to discover one of Barcelona\'s neighborhood and meeting your classmates.',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['html', 'css', 'bootstrap'],
      },
    ],
    facebook: 'https://www.facebook.com/alecsandra.serediuc',
    instagram: 'https://www.instagram.com/alecsandra_serediuc/',
    twitter: '',
    video: 'CPWM-SE7dhs',
    calendly: 'https://calendly.com/alecsandra-serediuc',
  },
  spanish: {
    name: 'Alexandrina Serediuc',
    email: 'alecsandra.serediuc@gmail.com',
    from: 'Republic of Moldova',
    livingIn: 'Barcelona',
    dateOfBirth: '29/04/1990',
    linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
    profilePicture: ProfilePicture,
    languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
    shortDescription: 'Desarrollador junior creativo con una fuerte voluntad de aprender y crecer',
    longDescription: [
      'Los últimos 5 meses fueron el mejor desafío hasta ahora.',
      'Aprender a programar y aplicarlo en los proyectos de bootcamp. Además de las habilidades técnicas, he aprendido a lidiar con errores / conflictos, aceptar críticas y ser un jugador de equipo. Tengo una mente curiosa y un fuerte deseo de crecer, descubrir y resolver nuevos desafíos.',
      'Tengo mi licenciatura en Administración Pública y trabajé los últimos 5 años en la industria del cine.',
      'Mi experiencia previa me permitió desarrollar la capacidad de planificar, desarrollar e implementar proyectos estratégicamente para lograr los objetivos del equipo.',
    ],
    github: 'https://github.com/Alecsundra',
    technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
    personalProjects: [
      {
        projectName: 'La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: 'link to project2',
        projectDescription: 'El proyecto del cliente real. Creación de una plataforma de compromiso para los fanáticos de La Pegatina (banda de música de rumba Catalana) basada en juegos (jugar con música, videos e imágenes). Usando la conexión con el back-end (aprendiéndolo al mismo tiempo), el usuario puede registrarse y conservar los puntos.',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react', 'youtube', 'node', 'mysql'],
      },
      {
        projectName: 'Hackathon-Hola Dulce',
        projectGithub: 'https://github.com/Hackaton-holadulce/Front',
        projectLink: '#',
        projectImage: HolaDulce,
        projectDescription: 'Two days remote hackathon, building an administartive page to manage the stock.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'mysql', 'node'],
      },
      {
        projectName: 'Barcelona Hackathon',
        projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'El cliente del hackathon: La Vanguardia (periódico español propiedad del Grupo Godó). Tuvimos que construir una plataforma de interacción, basada en juegos durante 24 horas. Fue una gran experiencia.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'bootstrap'],
      },
      {
        projectName: 'Animate',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectImage: Animate,
        projectLink: 'link to project2',
        projectDescription: 'Segundo proyecto Bootcamp, realizado en 4 semanas. Aprendimos y practicamos al mismo tiempo React.js, usando una API externa y paquetes npm. El proyecto ofrece una aplicación donde puedes encontrar (usando un filtro) eventos en Cataluña(usando la API Generalidad de Cataluña) y verlos en un mapa.',
        collaborators: ['Vlada Masko', 'Julie Brosse'],
        technologies: ['react', 'material', 'leaflet', 'css'],
      },
      {
        projectName: 'StreetsOfGracia',
        projectGithub: 'https://github.com/mireiaGomariz/project1',
        projectImage: Gracia,
        projectLink: 'https://mireiagomariz.github.io/project1/index.html',
        projectDescription: 'Primera semana del proyecto bootcamp. Excelente manera de descubrir uno de los barrios de Barcelona y conocer a tus compañeros de clase.',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['html', 'css', 'bootstrap'],
      },
    ],
    facebook: 'https://www.facebook.com/alecsandra.serediuc',
    instagram: 'https://www.instagram.com/alecsandra_serediuc/',
    twitter: '',
    video: 'CPWM-SE7dhs',
    calendly: 'https://calendly.com/alecsandra-serediuc',
  },
};
