import Vanguardia from '../img/projects/vanguardiaBG.jpg';
import Gracia from '../img/projects/graciaBG.jpg';
import Pegatina from '../img/projects/pegatinaBG.jpg';
import Animate from '../img/projects/animateBG.jpg';
import ProfilePicture from '../img/profiles/sandra.jpeg';


export const Sandra =
{
  english: {
    name: 'Alexandrina Serediuc',
    email: 'alecsandra.serediuc@gmail.com',
    from: 'Republic of Moldova',
    livingIn: 'Barcelona',
    dateOfBirth: '29/04/1990',
    linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
    profilePicture: ProfilePicture,
    languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
    shortDescription: 'I\'m a junior web develoer with a strong will to learn and grow',
    longDescription: [
      'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
      'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
      'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
    ],
    github: 'https://github.com/Alecsundra',
    technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
    personalProjects: [
      {
        projectName: 'La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: 'link to project2',
        projectDescription: 'The Real Client Project. Building an engagement platform for La Pegatina fans( music band of Catalan rumba) based on games ( play with music, videos and images). Using the connection with back-end(learning it in the same time), the user can register and keep the points.',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react', 'youtube', 'node', 'mysql'],
      },
      {
        projectName: 'Barcelona Hackathon',
        projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'The hackathon client- La Vanguardia(spanish newspaper owned by Grupo Godó).We had to build an engagement platform, based on games during 24 hours. It was a great experience.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'bootstrap'],
      },
      {
        projectName: 'Animate',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectImage: Animate,
        projectLink: 'link to project2',
        projectDescription: 'Second Bootcamp project, made in 4 weeks. We\'ve learned and practiced in the same time React.js, using an external API and npm packages. The project come up with an online app where you can find(using a filter) events in Catalunya(using the Generalidad API) and see them on a map.',
        collaborators: ['Vlada Masko', 'Julie Brosse'],
        technologies: ['react', 'material', 'leaflet', 'css'],
      },
      {
        projectName: 'StreetsOfGracia',
        projectGithub: 'https://github.com/mireiaGomariz/project1',
        projectImage: Gracia,
        projectLink: 'https://mireiagomariz.github.io/project1/index.html',
        projectDescription: 'First week bootcamp project. Great way to discover one of Barcelona\'s neighborhood and meeting your classmates.',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['html', 'css', 'bootstrap'],
      },
    ],
    facebook: 'https://www.facebook.com/alecsandra.serediuc',
    instagram: 'https://www.instagram.com/alecsandra_serediuc/',
    twitter: '',
    video: '',
    calendly: 'https://calendly.com/alecsandra-serediuc',
  },
  spanish: {
    name: 'Alexandrina Serediuc',
    email: 'alecsandra.serediuc@gmail.com',
    from: 'Republic of Moldova',
    livingIn: 'Barcelona',
    dateOfBirth: '29/04/1990',
    linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
    profilePicture: ProfilePicture,
    languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
    shortDescription: 'Soy un desarrollador web junior con una fuerte voluntad de aprender y crecer',
    longDescription: [
      'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
      'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
      'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
    ],
    github: 'https://github.com/Alecsundra',
    technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
    personalProjects: [
      {
        projectName: 'La Pegatina',
        projectGithub: 'https://github.com/rutabello/LaPegatina',
        projectImage: Pegatina,
        projectLink: 'link to project2',
        projectDescription: 'El proyecto del cliente real. Creación de una plataforma de compromiso para los fanáticos de La Pegatina (banda de música de rumba Catalana) basada en juegos (jugar con música, videos e imágenes). Usando la conexión con el back-end (aprendiéndolo al mismo tiempo), el usuario puede registrarse y conservar los puntos.',
        collaborators: ['Ruth Abelló', 'Lena Kujath'],
        technologies: ['react', 'youtube', 'node', 'mysql'],
      },
      {
        projectName: 'Barcelona Hackathon',
        projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
        projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
        projectImage: Vanguardia,
        projectDescription: 'El cliente del hackathon: La Vanguardia (periódico español propiedad del Grupo Godó). Tuvimos que construir una plataforma de interacción, basada en juegos durante 24 horas. Fue una gran experiencia.',
        collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['react', 'bootstrap'],
      },
      {
        projectName: 'Animate',
        projectGithub: 'https://github.com/masko-vl/animate',
        projectImage: Animate,
        projectLink: 'link to project2',
        projectDescription: 'Segundo proyecto Bootcamp, realizado en 4 semanas. Aprendimos y practicamos al mismo tiempo React.js, usando una API externa y paquetes npm. El proyecto ofrece una aplicación donde puedes encontrar (usando un filtro) eventos en Cataluña(usando la API Generalidad de Cataluña) y verlos en un mapa.',
        collaborators: ['Vlada Masko', 'Julie Brosse'],
        technologies: ['react', 'material', 'leaflet', 'css'],
      },
      {
        projectName: 'StreetsOfGracia',
        projectGithub: 'https://github.com/mireiaGomariz/project1',
        projectImage: Gracia,
        projectLink: 'https://mireiagomariz.github.io/project1/index.html',
        projectDescription: 'Primera semana del proyecto bootcamp. Excelente manera de descubrir uno de los barrios de Barcelona y conocer a tus compañeros de clase.',
        collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
        technologies: ['html', 'css', 'bootstrap'],
      },
    ],
    facebook: 'https://www.facebook.com/alecsandra.serediuc',
    instagram: 'https://www.instagram.com/alecsandra_serediuc/',
    twitter: '',
    video: '',
    calendly: 'https://calendly.com/alecsandra-serediuc',
  },
};
