export const StudentsList = [
  {
    english: {
      name: 'Your name 1',
      email: 'Your email 1',
      from: 'where are you from 1',
      livingIn: 'city where you live 1',
      dateOfBirth: 'dd/mm/yyyy 1',
      linkedin: 'your linkedin 1',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Short description about yourself, it will be on the landing page 1',
      longDescription: 'Long description about yourself, it will be on the profile page 1',
      github: 'github link 1',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'name of project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'name of project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Tu nombre 1',
      email: 'Tu email 1',
      from: 'de donde eres 1',
      livingIn: 'ciudad donde vives 1',
      dateOfBirth: 'dd/mm/yyyy 1',
      linkedin: 'tu linkedin 1',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Corta descripción sobre ti, estará en la landing page 1',
      longDescription: 'Larga descripción sobre ti, estará en la pagina del perfil 1',
      github: 'github link 1',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'nombre del project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'nombre project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
  },
  {
    english: {
      name: 'Your name 2',
      email: 'Your email 2',
      from: 'where are you from 2',
      livingIn: 'city where you live 2',
      dateOfBirth: 'dd/mm/yyyy 2',
      linkedin: 'your linkedin 2',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Short description about yourself, it will be on the landing page 2',
      longDescription: 'Long description about yourself, it will be on the profile page 2',
      github: 'github link 2',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'name of project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'name of project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Tu nombre 2',
      email: 'Tu email 2',
      from: 'de donde eres 2',
      livingIn: 'ciudad donde vives 2',
      dateOfBirth: 'dd/mm/yyyy 2',
      linkedin: 'tu linkedin 2',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Corta descripción sobre ti, estará en la landing page 2',
      longDescription: 'Larga descripción sobre ti, estará en la pagina del perfil 2',
      github: 'github link 2',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'nombre del project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'nombre project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
  },
  {
    english: {
      name: 'Your name 3',
      email: 'Your email 3',
      from: 'where are you from 3',
      livingIn: 'city where you live 3',
      dateOfBirth: 'dd/mm/yyyy 3',
      linkedin: 'your linkedin 3',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Short description about yourself, it will be on the landing page 3',
      longDescription: 'Long description about yourself, it will be on the profile page 3',
      github: 'github link 3',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'name of project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'name of project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Tu nombre 3',
      email: 'Tu email 3',
      from: 'de donde eres 3',
      livingIn: 'ciudad donde vives 3',
      dateOfBirth: 'dd/mm/yyyy 3',
      linkedin: 'tu linkedin 3',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Corta descripción sobre ti, estará en la landing page 3',
      longDescription: 'Larga descripción sobre ti, estará en la pagina del perfil 3',
      github: 'github link 3',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'nombre del project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'nombre project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
  },
  {
    english: {
      name: 'Your name 4',
      email: 'Your email 4',
      from: 'where are you from 4',
      livingIn: 'city where you live 4',
      dateOfBirth: 'dd/mm/yyyy 4',
      linkedin: 'your linkedin 4',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Short description about yourself, it will be on the landing page 4',
      longDescription: 'Long description about yourself, it will be on the profile page 4',
      github: 'github link 4',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'name of project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'name of project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Tu nombre 4',
      email: 'Tu email 4',
      from: 'de donde eres 4',
      livingIn: 'ciudad donde vives 4',
      dateOfBirth: 'dd/mm/yyyy 4',
      linkedin: 'tu linkedin 4',
      languages: ['language1', 'language2', 'language3'],
      shortDescription: 'Corta descripción sobre ti, estará en la landing page 4',
      longDescription: 'Larga descripción sobre ti, estará en la pagina del perfil 4',
      github: 'github link 4',
      technologies: ['technology 1', 'technology 2', 'technology 3', 'technology 4'],
      personalProjects: [
        {
          projectName: 'nombre del project1',
          projectGithub: 'github of project1',
          projectLink: 'link to project1',
          projectDescription: 'description about project1',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 1'],
        },
        {
          projectName: 'nombre project2',
          projectGithub: 'github of project2',
          projectLink: 'link to project2',
          projectDescription: 'description about project2',
          collaborators: ['collaborator1', 'collaborator2', 'collaborator3'],
          technologies: ['technologies used on project 2'],
        },
      ],
      socialNetwork: ['social network1', 'social network2'],
      video: 'video url',
      calendly: 'calendly link',
    },
  },
];
