import Montjuic from './img/projects/montjuicBG.jpg';
import PlayWith from './img/projects/playwithBG.jpg';
import Vanguardia from './img/projects/vanguardiaBG.jpg';
import Gracia from './img/projects/graciaBG.jpg';
import Pegatina from './img/projects/pegatinaBG.jpg';
import Animate from './img/projects/animateBG.jpg';
import RickAndMorty from './img/projects/rickMortyBG.jpg';
// import TestPicture from './img/profileTestPic.png';


export const StudentsList = [
  {
    english: {
      name: 'Lena Kujath',
      email: 'l.kujath@gmx.de',
      from: 'Germany',
      livingIn: 'Barcelona',
      dateOfBirth: '22/03/1993',
      linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQEe7SQNI6nB8Q/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=Kfmkt6W9ye5OvZOXwLq1IsduwgP1jA7EBCpJLj9SJfs',
      languages: ['german', 'english', 'spanish', 'french'],
      shortDescription: 'Curious programmer, eager to constantely learn new things and passionate about solving interesting problems creatively.',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/LenKuj',
      technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'Montjuic Webpage',
          projectImage: Montjuic,
          projectGithub: 'https://github.com/LenKuj/WCProject',
          projectLink: 'https://lenkuj.github.io/WCProject/',
          projectDescription: 'A webpage dedicated to the discovery of the beautiful and culturaly interesting places of the Montjuic (Barcelona)',
          collaborators: ['Macarena Mariani', 'Binay Timilsina'],
          technologies: ['bootstrap', 'html', 'css', 'javascript'],
        },
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'playwith.es',
          projectDescription: 'Gamification of music discovery',
          collaborators: ['Ruth Abelló', 'Ailina Ozola'],
          technologies: ['react', 'css'],
        },
      ],
      facebook: 'https://www.facebook.com/lena.kujath/',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Lena Kujath',
      email: 'l.kujath@gmx.de',
      from: 'Alemania',
      livingIn: 'Barcelona',
      dateOfBirth: '22/03/1993',
      linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQEe7SQNI6nB8Q/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=Kfmkt6W9ye5OvZOXwLq1IsduwgP1jA7EBCpJLj9SJfs',
      languages: ['german', 'english', 'spanish', 'french'],
      shortDescription: 'Programadora curiosa, con ganas de aprender siempre y apasionada de resolver problemas interesantes creativamente.',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/LenKuj',
      technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'Montjuic Webpage',
          projectGithub: 'https://github.com/LenKuj/WCProject',
          projectImage: Montjuic,
          projectLink: 'https://lenkuj.github.io/WCProject/',
          projectDescription: 'Una página web dedicada a encontrar los lugares hermosos y culturalmente interesantes de Montjuic (Barcelona)',
          collaborators: ['Macarena Mariani', 'Binay Timilsina'],
          technologies: ['bootstrap', 'html', 'css', 'javascript'],
        },
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'playwith.es',
          projectDescription: 'Te permite encontrar nueva música de todo el mundo jugando',
          collaborators: ['Ruth Abelló', 'Ailina Ozola'],
          technologies: ['react', 'css'],
        },
      ],
      facebook: 'https://www.facebook.com/lena.kujath/',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'calendly link',
    },
  },
  {
    english: {
      name: 'Ailina Ozola',
      email: 'ailuozols@gmail.com',
      from: 'Argentina',
      livingIn: 'Barcelona',
      dateOfBirth: '11/02/1998',
      linkedin: 'https://www.linkedin.com/in/ailinaozola/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQERh7BUkEyEsQ/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=DaPUHf9DqatscI15-48pfg1-zl17m4TdNhuPnpTFoKU',
      languages: ['spanish', 'english', 'portuguese'],
      shortDescription: 'The youngest of the group with 22 years of life and the rest to code',
      longDescription: [
        'I used to cook for money but now i would code for food!',
        'In the past working at the kitchen and in customer service teached me how to be a team player, about perseverance, working under pressure and to adapt myself to different scenarios.',
        'During this long learning journey I discovered that I like both the backend and the frontend (not because the bootcamp title is fullstack developer!: P).',
        'I enjoy combining the logical part and the creative part (for which I feel that having studied art developed some knowledge about the display, the design that is carried out on the elements to improve the user experience so the product is more effective).',
        'Now for the first time i have the opportunity to work in something that I am passionate about, it makes me grow as a person, which constantly involves interesting challenges.',
      ],
      github: 'https://github.com/AlundraOz',
      technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
      personalProjects: [
        {
          projectName: 'LaVanguardia\'s game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia',
          projectLink: 'link to project1',
          projectDescription: 'Creation of a new and innovative game section for newspaper\'s users and personalizing it and integrating it into their digital plataform in order to create more engagement.',
          collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
          technologies: ['react', 'javascript', 'bootstrap'],
        },
        {
          projectName: 'PlayWith',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'PlayWith it\'s a fun way to discover new music from all around the world while playing a quizz game',
          collaborators: ['Ruth Abelló', 'Lena Kujath'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
    },
    spanish: {
      name: 'Ailina Ozola',
      email: 'ailuozols@gmail.com',
      from: 'Argentina',
      livingIn: 'Barcelona',
      dateOfBirth: '11/02/1998',
      linkedin: 'https://www.linkedin.com/in/ailinaozola/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQERh7BUkEyEsQ/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=DaPUHf9DqatscI15-48pfg1-zl17m4TdNhuPnpTFoKU',
      languages: ['spanish', 'english', 'portuguese'],
      shortDescription: 'The youngest of the group with 22 years of life and the rest to code',
      longDescription: [
        'I used to cook for money but now i would code for food!',
        'In the past working at the kitchen and in customer service teached me how to be a team player, about perseverance, working under pressure and to adapt myself to different scenarios.',
        'During this long learning journey I discovered that I like both the backend and the frontend (not because the bootcamp title is fullstack developer!: P).',
        'I enjoy combining the logical part and the creative part (for which I feel that having studied art developed some knowledge about the display, the design that is carried out on the elements to improve the user experience so the product is more effective).',
        'Now for the first time i have the opportunity to work in something that I am passionate about, it makes me grow as a person, which constantly involves interesting challenges.',
      ],
      github: 'https://github.com/AlundraOz',
      technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
      personalProjects: [
        {
          projectName: 'LaVanguardia\'s game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia',
          projectLink: 'link to project1',
          projectDescription: 'Creation of a new and innovative game section for newspaper\'s users and personalizing it and integrating it into their digital plataform in order to create more engagement.',
          collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
          technologies: ['react', 'javascript', 'bootstrap'],
        },
        {
          projectName: 'PlayWith',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'PlayWith it\'s a fun way to discover new music from all around the world while playing a quizz game',
          collaborators: ['Ruth Abelló', 'Lena Kujath'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
    },
  },
  {
    english: {
      name: 'Alexandrina Serediuc',
      email: 'alecsandra.serediuc@gmail.com',
      from: 'Republic of Moldova',
      livingIn: 'Barcelona',
      dateOfBirth: '29/04/1990',
      linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQG_1_93he6B_w/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=zSLmpk6cgh3oKfBtGWueLlMk8ciQtFPBbhBpq2ApnOc',
      languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
      shortDescription: 'I\'m a junior web develoer with a strong will to learn and grow',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/Alecsundra',
      technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
      personalProjects: [
        {
          projectName: 'StreetsOfGracia',
          projectGithub: 'https://github.com/mireiaGomariz/project1',
          projectImage: Gracia,
          projectLink: 'https://mireiagomariz.github.io/project1/index.html',
          projectDescription: 'First week bootcamp project. Great way to discover one of Barcelona\'s neighborhood and meeting your classmates.',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['html', 'css', 'bootstrap'],
        },
        {
          projectName: 'Animate',
          projectGithub: 'https://github.com/masko-vl/animate',
          projectImage: Animate,
          projectLink: 'link to project2',
          projectDescription: 'Second Bootcamp project, made in 4 weeks. We\'ve learned and practiced in the same time React.js, using an external API and npm packages. The project come up with an online app where you can find(using a filter) events in Catalunya(using the Generalidad API) and see them on a map.',
          collaborators: ['Vlada Masko', 'Julie Brosse'],
          technologies: ['react', 'material', 'leaflet', 'css'],
        },
        {
          projectName: 'Barcelona Hackathon',
          projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
          projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
          projectImage: Vanguardia,
          projectDescription: 'The hackathon client- La Vanguardia(spanish newspaper owned by Grupo Godó).We had to build an engagement platform, based on games during 24 hours. It was a great experience.',
          collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['react', 'bootstrap'],
        },
        {
          projectName: 'La Pegatina',
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectImage: Pegatina,
          projectLink: 'link to project2',
          projectDescription: 'The Real Client Project. Building an engagement platform for La Pegatina fans( music band of Catalan rumba) based on games ( play with music, videos and images). Using the connection with back-end(learning it in the same time), the user can register and keep the points.',
          collaborators: ['Ruth Abelló', 'Lena Kujath'],
          technologies: ['react', 'youtube', 'node', 'mysql'],
        },
      ],
      facebook: 'https://www.facebook.com/alecsandra.serediuc',
      instagram: 'https://www.instagram.com/alecsandra_serediuc/',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/alecsandra-serediuc',
    },
    spanish: {
      name: 'Alexandrina Serediuc',
      email: 'alecsandra.serediuc@gmail.com',
      from: 'Republic of Moldova',
      livingIn: 'Barcelona',
      dateOfBirth: '29/04/1990',
      linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQG_1_93he6B_w/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=zSLmpk6cgh3oKfBtGWueLlMk8ciQtFPBbhBpq2ApnOc',
      languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
      shortDescription: 'Soy un desarrollador web junior con una fuerte voluntad de aprender y crecer',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/Alecsundra',
      technologies: ['react', 'javascript', 'node', 'mysql', 'html', 'css', 'git', 'scrum'],
      personalProjects: [
        {
          projectName: 'StreetsOfGracia',
          projectGithub: 'https://github.com/mireiaGomariz/project1',
          projectImage: Gracia,
          projectLink: 'https://mireiagomariz.github.io/project1/index.html',
          projectDescription: 'Primera semana del proyecto bootcamp. Excelente manera de descubrir uno de los barrios de Barcelona y conocer a tus compañeros de clase.',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['html', 'css', 'bootstrap'],
        },
        {
          projectName: 'Animate',
          projectGithub: 'https://github.com/masko-vl/animate',
          projectImage: Animate,
          projectLink: 'link to project2',
          projectDescription: 'Segundo proyecto Bootcamp, realizado en 4 semanas. Aprendimos y practicamos al mismo tiempo React.js, usando una API externa y paquetes npm. El proyecto ofrece una aplicación donde puedes encontrar (usando un filtro) eventos en Cataluña(usando la API Generalidad de Cataluña) y verlos en un mapa.',
          collaborators: ['Vlada Masko', 'Julie Brosse'],
          technologies: ['react', 'material', 'leaflet', 'css'],
        },
        {
          projectName: 'Barcelona Hackathon',
          projectGithub: 'https://github.com/rutabello/Barcelona_Hackaton',
          projectLink: 'https://nervous-dubinsky-07cde8.netlify.app/',
          projectImage: Vanguardia,
          projectDescription: 'El cliente del hackathon: La Vanguardia (periódico español propiedad del Grupo Godó). Tuvimos que construir una plataforma de interacción, basada en juegos durante 24 horas. Fue una gran experiencia.',
          collaborators: ['Vlada Masko', 'Julie Brosse', 'Ruth Abelló', 'Lena Kujath', 'Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['react', 'bootstrap'],
        },
        {
          projectName: 'La Pegatina',
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectImage: Pegatina,
          projectLink: 'link to project2',
          projectDescription: 'El proyecto del cliente real. Creación de una plataforma de compromiso para los fanáticos de La Pegatina (banda de música de rumba Catalana) basada en juegos (jugar con música, videos e imágenes). Usando la conexión con el back-end (aprendiéndolo al mismo tiempo), el usuario puede registrarse y conservar los puntos.',
          collaborators: ['Ruth Abelló', 'Lena Kujath'],
          technologies: ['react', 'youtube', 'node', 'mysql'],
        },
      ],
      facebook: 'https://www.facebook.com/alecsandra.serediuc',
      instagram: 'https://www.instagram.com/alecsandra_serediuc/',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/alecsandra-serediuc',
    },
  },
  {
    english: {
      name: 'Vlada Masko',
      email: 'vlada.masko0@gmail.com',
      from: 'Ukraine',
      livingIn: 'Barcelona',
      dateOfBirth: '13/12/1995',
      linkedin: 'https://www.linkedin.com/in/vlada-masko/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQFJz3JChtHfYg/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=p40HltZjmG_3z7MtGtOns8sOvhkJOq0D11yF_3LeYu8',
      languages: ['spanish', 'english', 'ukranian', 'russian'],
      shortDescription: 'Short description about yourself, it will be on the landing page',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/masko-vl',
      technologies: ['javascript', 'react', 'node', 'php', 'html', 'css', 'bootstrap', 'jquery', 'mysql', 'scrum'],
      personalProjects: [
        {
          projectName: 'ANÍMATE',
          projectImage: Animate,
          projectGithub: 'https://github.com/masko-vl/animategithub of project1',
          projectLink: 'https://animate.cat/',
          projectDescription: 'description about project1',
          collaborators: ['Julie Brosse', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
        {
          projectName: 'La Vanguardia Game Section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'description about project2',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Julie Brosse'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/vlada-masko/30min',
    },
    spanish: {
      name: 'Vlada Masko',
      email: 'vlada.masko0@gmail.com',
      from: 'Ukraine',
      livingIn: 'Barcelona',
      dateOfBirth: '13/12/1995',
      linkedin: 'https://www.linkedin.com/in/vlada-masko/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C4D03AQFJz3JChtHfYg/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=p40HltZjmG_3z7MtGtOns8sOvhkJOq0D11yF_3LeYu8',
      languages: ['spanish', 'english', 'ukranian', 'russian'],
      shortDescription: 'Short description about yourself, it will be on the landing page',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/masko-vl',
      technologies: ['javascript', 'react', 'node', 'php', 'html', 'css', 'bootstrap', 'jquery', 'mysql', 'scrum'],
      personalProjects: [
        {
          projectName: 'ANÍMATE',
          projectImage: Animate,
          projectGithub: 'https://github.com/masko-vl/animategithub of project1',
          projectLink: 'https://animate.cat/',
          projectDescription: 'description about project1',
          collaborators: ['Julie Brosse', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
        {
          projectName: 'La Vanguardia Game Section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'description about project2',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Julie Brosse'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: '',
      calendly: 'https://calendly.com/vlada-masko/30min',
    },
  },
  {
    english: {
      name: 'Mireia Gomariz',
      email: 'mireiapgomariz@gmail.com',
      from: 'Barcelona',
      livingIn: 'Barcelona',
      dateOfBirth: '07/08/1993',
      linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQEo28zXbNhgYA/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=r_Qk2pq-v8T43marFV39lhoPFc3ip_JCzkHTL3IXLwM',
      languages: ['spanish', 'english', 'catalan'],
      shortDescription: 'FullStack web developer with sales and sanitary background',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/mireiaGomariz',
      technologies: ['react', 'node', 'javascript'],
      personalProjects: [
        {
          projectName: 'La Vanguardia game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
          collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
          technologies: ['react', 'node'],
        },
        {
          projectName: 'ShowMeWhatYouGot',
          projectImage: RickAndMorty,
          projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
          projectLink: 'link to project2',
          projectDescription: 'Game web page about Rick and Morty show',
          collaborators: ['Maca Mariani'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: 'https://twitter.com/GomarizMireia',
      video: '',
      calendly: 'https://calendly.com/mireiapgomariz',
    },
    spanish: {
      name: 'Mireia Gomariz',
      email: 'mireiapgomariz@gmail.com',
      from: 'Barcelona',
      livingIn: 'Barcelona',
      dateOfBirth: '07/08/1993',
      linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQEo28zXbNhgYA/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=r_Qk2pq-v8T43marFV39lhoPFc3ip_JCzkHTL3IXLwM',
      languages: ['spanish', 'english', 'catalan'],
      shortDescription: 'FullStack web developer with sales and sanitary background',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/mireiaGomariz',
      technologies: ['react', 'node', 'javascript'],
      personalProjects: [
        {
          projectName: 'La Vanguardia game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
          collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
          technologies: ['react', 'node'],
        },
        {
          projectName: 'ShowMeWhatYouGot',
          projectImage: RickAndMorty,
          projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
          projectLink: 'link to project2',
          projectDescription: 'Game web page about Rick and Morty show',
          collaborators: ['Maca Mariani'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: 'https://twitter.com/GomarizMireia',
      video: '',
      calendly: 'https://calendly.com/mireiapgomariz',
    },
  },
  {
    english: {
      name: 'Ruth Abelló',
      email: 'rut.abello@gmail.com',
      from: 'Reus',
      livingIn: 'Gelida',
      dateOfBirth: '14/09/1987',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQFwB_i-xWlnFQ/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=ege0l8lIegqKlBinMvMahsUeEqBTTL8tx3Hw079EBqQ',
      linkedin: 'https://www.linkedin.com/in/ruth-abello-cort/',
      languages: ['catalan', 'spanish', 'english'],
      technologies: ['react', 'node', 'javascript'],
      shortDescription: 'Former journalist converted into a passionate front-end developer',
      longDescription: [
        'People keep asking me how come a journalist is now a web developer.',
        'My answer is always the same: "The true question here should be \'How come a web developer used to be a journalist?\'".',
        'Because, considering my background, my passion for everything related to science and tech, what\'s not clear at all is how I ended up in journalism school.It took me 8 years getting back again to the right path(not that journalism wasn\'t right, I also had a lot of fun and learned a lot there, but, you know...), but here I am.',
        'I\'ve cried, dealt with frustration, learned so much in such a short time, proved myself wrong, failed, and, finally, succeeded.What I like the most, the infinite amount of opportunities to keep learning and never stop doing it, because technology is in constant change, and so am I.',
      ],
      github: 'https://github.com/rutabello/',
      personalProjects: [
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'Play With lets you learn new worldwide music while playing with it',
          collaborators: ['Ailina Ozola', 'Lena Kujath'],
          technologies: ['react'],
        },
        {
          projectName: 'Play With La Pegatina',
          projectImage: Pegatina,
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectLink: '',
          projectDescription: 'Prove no-one knows more than you do about La Pegatina by playing with their music, videos and pictures. Make points and exchange them for concert tickets, trips, music and meet&greets',
          collaborators: ['Lena Kujath', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'It8mlr2s9kI',
      calendly: 'https://calendly.com/ruthere',
    },
    spanish: {
      name: 'Ruth Abelló',
      email: 'rut.abello@gmail.com',
      from: 'Reus',
      livingIn: 'Gelida',
      dateOfBirth: '14/09/1987',
      profilePicture: 'https://media-exp1.licdn.com/dms/image/C5603AQFwB_i-xWlnFQ/profile-displayphoto-shrink_800_800/0?e=1594252800&v=beta&t=ege0l8lIegqKlBinMvMahsUeEqBTTL8tx3Hw079EBqQ',
      linkedin: 'https://www.linkedin.com/in/ruth-abello-cort-/',
      languages: ['catalan', 'spanish', 'english'],
      technologies: ['react', 'node', 'javascript'],
      shortDescription: 'Periodista reconvertida en apasionada por la programación font-end',
      longDescription: [
        'La gente que me conoce no para de preguntarme qué hacía una periodista estudiando para ser programadora.',
        'Mi respuesta es siempre la misma: "La pregunta, realmente, debería ser \'Qué hacía una programadora trabajando de periodista\'".',
        'Y es que, tomando en consideración mi experiencia, mi pasión desde siempre por los números y todo lo relacionado con la ciencia y le tecnología, lo que no está nada claro es cómo acabé en la facultad de periodismo. Me llevó 8 años de ejercicio del periodismo darme cuenta que ese no era mi camino (no es que no fuera un buen camino, lo pasé muy bien y aprendí mucho, pero...) y encontrar el camino que sí era correcto para mí, pero aquí estoy.',
        'He llorado, me ha tocado lidiar con la frustración, he aprendido mucho en muy poco tiempo, me he equivocado y he aprendido de cada error. Lo que más me gusta de todo este cambio: las oportunidades infinitas que ofrece de seguir aprendiendo y nunca dejar de hacerlo, porque la tecnología está en constante cambio. Igual que yo.',
      ],
      github: 'https://github.com/rutabello/',
      personalProjects: [
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'Play With es una herramienta que te permite descubrir nueva música de todo el mundo a medida que juegas con ella.',
          collaborators: ['Ailina Ozola', 'Lena Kujath'],
          technologies: ['react'],
        },
        {
          projectName: 'Juega con La Pegatina',
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectImage: Pegatina,
          projectLink: '',
          projectDescription: 'Demuestra que eres quien más sabe sobre La Pegatina mientras juegas con su música, sus fotos y sus vídeos. Gana puntos y cámbialos por entradas a conciertos, meet&greets, música y viajes!',
          collaborators: ['Lena Kujath', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'It8mlr2s9kI',
      calendly: 'https://calendly.com/ruthere',
    },
  },
];
