import Montjuic from './img/projects/montjuic.png';
import PlayWith from './img/projects/playwith.png';
import Vanguardia from './img/projects/vanguardia.png';
import TestPicture from './img/profileTestPic.png';


export const StudentsList = [
  {
    english: {
      name: 'Lena Kujath',
      email: 'l.kujath@gmx.de',
      from: 'Germany',
      livingIn: 'Barcelona',
      dateOfBirth: '22/03/1993',
      linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
      profilePicture: TestPicture,
      languages: ['german', 'english', 'spanish', 'french'],
      shortDescription: 'Curious programmer, eager to constantely learn new things and passionate about solving interesting problems creatively.',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/LenKuj',
      technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'Montjuic Webpage',
          projectImage: Montjuic,
          projectGithub: 'https://github.com/LenKuj/WCProject',
          projectLink: 'https://lenkuj.github.io/WCProject/',
          projectDescription: 'A webpage dedicated to the discovery of the beautiful and culturaly interesting places of the Montjuic (Barcelona)',
          collaborators: ['Macarena Mariani', 'Binay Timilsina'],
          technologies: ['bootstrap', 'html', 'css', 'javascript'],
        },
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'playwith.es',
          projectDescription: 'Gamification of music discovery',
          collaborators: ['Ruth Abelló Cort', 'Ailina Ozola'],
          technologies: ['react', 'css'],
        },
      ],
      facebook: 'https://www.facebook.com/lena.kujath/',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'calendly link',
    },
    spanish: {
      name: 'Lena Kujath',
      email: 'l.kujath@gmx.de',
      from: 'Alemania',
      livingIn: 'Barcelona',
      dateOfBirth: '22/03/1993',
      linkedin: 'https://www.linkedin.com/in/lena-kujath-85a719198',
      profilePicture: TestPicture,
      languages: ['german', 'english', 'spanish', 'french'],
      shortDescription: 'Programadora curiosa, con ganas de aprender siempre y apasionada de resolver problemas interesantes creativamente.',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/LenKuj',
      technologies: ['react', 'javascript', 'html', 'css', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'Montjuic Webpage',
          projectGithub: 'https://github.com/LenKuj/WCProject',
          projectImage: Montjuic,
          projectLink: 'https://lenkuj.github.io/WCProject/',
          projectDescription: 'Una página web dedicada a encontrar los lugares hermosos y culturalmente interesantes de Montjuic (Barcelona)',
          collaborators: ['Macarena Mariani', 'Binay Timilsina'],
          technologies: ['bootstrap', 'html', 'css', 'javascript'],
        },
        {
          projectName: 'Play With',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'playwith.es',
          projectDescription: 'Te permite encontrar nueva música de todo el mundo jugando',
          collaborators: ['Ruth Abelló Cort', 'Ailina Ozola'],
          technologies: ['react', 'css'],
        },
      ],
      facebook: 'https://www.facebook.com/lena.kujath/',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'calendly link',
    },
  },
  {
    english: {
      name: 'Ailina Ozola',
      email: 'ailuozols@gmail.com',
      from: 'Argentina',
      livingIn: 'Barcelona',
      dateOfBirth: '11/02/1998',
      linkedin: 'https://www.linkedin.com/in/ailinaozola/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'portuguese'],
      shortDescription: 'The youngest of the group with 22 years of life and the rest to code',
      longDescription: [
        'I used to cook for money but now i would code for food!',
        'In the past working at the kitchen and in customer service teached me how to be a team player, about perseverance, working under pressure and to adapt myself to different scenarios.',
        'During this long learning journey I discovered that I like both the backend and the frontend (not because the bootcamp title is fullstack developer!: P).',
        'I enjoy combining the logical part and the creative part (for which I feel that having studied art developed some knowledge about the display, the design that is carried out on the elements to improve the user experience so the product is more effective).',
        'Now for the first time i have the opportunity to work in something that I am passionate about, it makes me grow as a person, which constantly involves interesting challenges.',
      ],
      github: 'https://github.com/AlundraOz',
      technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
      personalProjects: [
        {
          projectName: 'LaVanguardia\'s game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia',
          projectLink: 'link to project1',
          projectDescription: 'Creation of a new and innovative game section for newspaper\'s users and personalizing it and integrating it into their digital plataform in order to create more engagement.',
          collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
          technologies: ['react', 'javascript', 'bootstrap'],
        },
        {
          projectName: 'PlayWith',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'PlayWith it\'s a fun way to discover new music from all around the world while playing a quizz game',
          collaborators: ['Rut Abello', 'Lena Kujath'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
    },
    spanish: {
      name: 'Ailina Ozola',
      email: 'ailuozols@gmail.com',
      from: 'Argentina',
      livingIn: 'Barcelona',
      dateOfBirth: '11/02/1998',
      linkedin: 'https://www.linkedin.com/in/ailinaozola/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'portuguese'],
      shortDescription: 'The youngest of the group with 22 years of life and the rest to code',
      longDescription: [
        'I used to cook for money but now i would code for food!',
        'In the past working at the kitchen and in customer service teached me how to be a team player, about perseverance, working under pressure and to adapt myself to different scenarios.',
        'During this long learning journey I discovered that I like both the backend and the frontend (not because the bootcamp title is fullstack developer!: P).',
        'I enjoy combining the logical part and the creative part (for which I feel that having studied art developed some knowledge about the display, the design that is carried out on the elements to improve the user experience so the product is more effective).',
        'Now for the first time i have the opportunity to work in something that I am passionate about, it makes me grow as a person, which constantly involves interesting challenges.',
      ],
      github: 'https://github.com/AlundraOz',
      technologies: ['react', 'node', 'git', 'mysql', 'javascript', 'bootstrap'],
      personalProjects: [
        {
          projectName: 'LaVanguardia\'s game section',
          projectImage: Vanguardia,
          projectGithub: 'https://github.com/LaVanguardia',
          projectLink: 'link to project1',
          projectDescription: 'Creation of a new and innovative game section for newspaper\'s users and personalizing it and integrating it into their digital plataform in order to create more engagement.',
          collaborators: ['Vlada Masko', 'Mireia Gomariz', 'Julie Brosse'],
          technologies: ['react', 'javascript', 'bootstrap'],
        },
        {
          projectName: 'PlayWith',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/rutabello/PlayWith',
          projectLink: 'https://playwith.es/',
          projectDescription: 'PlayWith it\'s a fun way to discover new music from all around the world while playing a quizz game',
          collaborators: ['Rut Abello', 'Lena Kujath'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/ailuozols/30min?month=2020-04',
    },
  },
  {
    english: {
      name: 'Alexandrina Serediuc',
      email: 'alecsandra.serediuc@gmail.com',
      from: 'Republic of Moldova',
      livingIn: 'Barcelona',
      dateOfBirth: '29/04/1990',
      linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
      profilePicture: TestPicture,
      languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
      shortDescription: 'I\'m a junior web develoer with a strong will to learn and grow',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/Alecsundra',
      technologies: ['react', 'javascript', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'StreetsOfGracia',
          projectGithub: 'https://github.com/mireiaGomariz/project1',
          projectImage: PlayWith,
          projectLink: 'link to project1',
          projectDescription: 'First bootcamp project, made in one week (the first week of the bootcamp)with HTML,CSS and Bootstrap.Great way of meeting all the classmates by starting working as a team right from the start.',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['html', 'css', 'bootstrap'],
        },
        {
          projectName: 'Animate',
          projectGithub: 'https://github.com/masko-vl/animate',
          projectImage: PlayWith,
          projectLink: 'link to project2',
          projectDescription: 'Second Bootcamp project, made in 4 weeks. We leaned and practice in the same time Rect, using an external API and npm packages',
          collaborators: ['Vlada Masko', 'Julie Brosse'],
          technologies: ['react', 'material', 'leaflet'],
        },
        {
          projectName: 'La Pegatina',
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectImage: PlayWith,
          projectLink: 'link to project2',
          projectDescription: 'The real client Project. Using and learning backend too ',
          collaborators: ['Rut Abelló', 'Lena Kujath'],
          technologies: ['react', 'youtube'],
        },
      ],
      facebook: 'https://www.facebook.com/alecsandra.serediuc',
      instagram: 'https://www.instagram.com/alecsandra_serediuc/',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/alecsandra-serediuc',
    },
    spanish: {
      name: 'Alexandrina Serediuc',
      email: 'alecsandra.serediuc@gmail.com',
      from: 'Republic of Moldova',
      livingIn: 'Barcelona',
      dateOfBirth: '29/04/1990',
      linkedin: 'https://www.linkedin.com/in/alexandrina-serediuc-a33678195/',
      profilePicture: TestPicture,
      languages: ['romanian', 'russian', 'english', 'italian', 'spanish'],
      shortDescription: 'I\'m a junior web develoer with a strong will to learn and grow',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/Alecsundra',
      technologies: ['react', 'javaScript', 'node', 'mysql'],
      personalProjects: [
        {
          projectName: 'StreetsOfGracia',
          projectGithub: 'https://github.com/mireiaGomariz/project1',
          projectImage: PlayWith,
          projectLink: 'link to project1',
          projectDescription: 'First bootcamp project, made in one week (the first week of the bootcamp)with HTML,CSS and Bootstrap.Great way of meeting all the classmates by starting working as a team right from the start.',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola'],
          technologies: ['html', 'css', 'bootstrap'],
        },
        {
          projectName: 'Animate',
          projectGithub: 'https://github.com/masko-vl/animate',
          projectImage: PlayWith,
          projectLink: 'link to project2',
          projectDescription: 'Second Bootcamp project, made in 4 weeks. We leaned and practice in the same time Rect, using an external API and npm packages',
          collaborators: ['Vlada Masko', 'Julie Brosse'],
          technologies: ['react', 'material', 'leaflet'],
        },
        {
          projectName: 'La Pegatina',
          projectGithub: 'https://github.com/rutabello/LaPegatina',
          projectImage: PlayWith,
          projectLink: 'link to project2',
          projectDescription: 'The real client Project. Using and learning backend too ',
          collaborators: ['Rut Abelló', 'Lena Kujath'],
          technologies: ['react', 'youtube'],
        },
      ],
      facebook: 'https://www.facebook.com/alecsandra.serediuc',
      instagram: 'https://www.instagram.com/alecsandra_serediuc/',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/alecsandra-serediuc',
    },
  },
  {
    english: {
      name: 'Vlada Masko',
      email: 'vlada.masko0@gmail.com',
      from: 'Ukraine',
      livingIn: 'Barcelona',
      dateOfBirth: '13/12/1995',
      linkedin: 'https://www.linkedin.com/in/vlada-masko/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'ukranian', 'russian'],
      shortDescription: 'Short description about yourself, it will be on the landing page',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/masko-vl',
      technologies: ['javascript', 'react', 'node', 'php', 'html', 'css', 'bootstrap', 'jquery', 'mysql', 'scrum'],
      personalProjects: [
        {
          projectName: 'ANÍMATE',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/masko-vl/animategithub of project1',
          projectLink: 'https://animate.cat/',
          projectDescription: 'description about project1',
          collaborators: ['Julie Brosse', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
        {
          projectName: 'La Vanguardia Game Section',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'description about project2',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Julie Brosse'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/vlada-masko/30min',
    },
    spanish: {
      name: 'Vlada Masko',
      email: 'vlada.masko0@gmail.com',
      from: 'Ukraine',
      livingIn: 'Barcelona',
      dateOfBirth: '13/12/1995',
      linkedin: 'https://www.linkedin.com/in/vlada-masko/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'ukranian', 'russian'],
      shortDescription: 'Short description about yourself, it will be on the landing page',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/masko-vl',
      technologies: ['javascript', 'react', 'node', 'php', 'html', 'css', 'bootstrap', 'jquery', 'mysql', 'scrum'],
      personalProjects: [
        {
          projectName: 'ANÍMATE',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/masko-vl/animategithub of project1',
          projectLink: 'https://animate.cat/',
          projectDescription: 'description about project1',
          collaborators: ['Julie Brosse', 'Alexandrina Serediuc'],
          technologies: ['react'],
        },
        {
          projectName: 'La Vanguardia Game Section',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'description about project2',
          collaborators: ['Mireia Gomariz', 'Ailina Ozola', 'Julie Brosse'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: '',
      video: 'video url',
      calendly: 'https://calendly.com/vlada-masko/30min',
    },
  },
  {
    english: {
      name: 'Mireia Gomariz',
      email: 'mireiapgomariz@gmail.com',
      from: 'Barcelona',
      livingIn: 'Barcelona',
      dateOfBirth: '07/08/1993',
      linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'catalan'],
      shortDescription: 'FullStack web developer with sales and sanitary background',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/mireiaGomariz',
      technologies: ['react', 'node', 'javascript'],
      personalProjects: [
        {
          projectName: 'La Vanguardia game section',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
          collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
          technologies: ['react', 'node'],
        },
        {
          projectName: 'ShowMeWhatYouGot',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
          projectLink: 'link to project2',
          projectDescription: 'Game web page about Rick and Morty show',
          collaborators: ['Maca Mariani'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: 'https://twitter.com/GomarizMireia',
      video: 'video url',
      calendly: 'https://calendly.com/mireiapgomariz',
    },
    spanish: {
      name: 'Mireia Gomariz',
      email: 'mireiapgomariz@gmail.com',
      from: 'Barcelona',
      livingIn: 'Barcelona',
      dateOfBirth: '07/08/1993',
      linkedin: 'https://www.linkedin.com/in/mireia-gom%C3%A0riz-8a7a0489/',
      profilePicture: TestPicture,
      languages: ['spanish', 'english', 'catalan'],
      shortDescription: 'FullStack web developer with sales and sanitary background',
      longDescription: [
        'Bacon ipsum dolor amet short ribs bacon frankfurter, ball tip shankle tri-tip chicken jerky turkey pork belly. Leberkas filet mignon sirloin tenderloin pork loin boudin sausage shoulder. Brisket short loin t-bone prosciutto pork belly hamburger pork chop shank meatball beef ribs fatback cupim frankfurter tenderloin andouille. Filet mignon turkey kevin, kielbasa ball tip jerky picanha. Frankfurter turducken tongue filet mignon, alcatra pig short loin bacon.',
        'Ball tip bresaola shoulder ham hock, cow burgdoggen shank ground round flank prosciutto. Swine turkey burgdoggen filet mignon biltong venison prosciutto kielbasa beef ribs spare ribs kevin. Drumstick kielbasa hamburger tongue ham hock t-bone. Landjaeger chicken hamburger chislic, swine prosciutto tail corned beef. Chuck frankfurter pork tail bresaola cupim.',
        'Jowl leberkas fatback biltong tongue turducken pig ground round. Prosciutto meatloaf ham hock pork cow. Short loin porchetta fatback cow. Frankfurter hamburger landjaeger andouille, pastrami tri-tip ball tip beef ribs short loin kevin rump brisket pork belly pork loin. T-bone pancetta flank, tenderloin beef ribs ham sirloin chuck pork loin beef turkey.',
      ],
      github: 'https://github.com/mireiaGomariz',
      technologies: ['react', 'node', 'javascript'],
      personalProjects: [
        {
          projectName: 'La Vanguardia game section',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/LaVanguardia/LaVanguardia',
          projectLink: 'https://zen-shaw-4b92a9.netlify.app/',
          projectDescription: 'We are creating a Game section for La Vanguardia newspaper, one of the most important in the country',
          collaborators: ['Julie Brosse', 'Vlada Masko', 'Ailina Ozola'],
          technologies: ['react', 'node'],
        },
        {
          projectName: 'ShowMeWhatYouGot',
          projectImage: PlayWith,
          projectGithub: 'https://github.com/mireiaGomariz/rick-morty',
          projectLink: 'link to project2',
          projectDescription: 'Game web page about Rick and Morty show',
          collaborators: ['Maca Mariani'],
          technologies: ['react'],
        },
      ],
      facebook: '',
      instagram: '',
      twitter: 'https://twitter.com/GomarizMireia',
      video: 'video url',
      calendly: 'https://calendly.com/mireiapgomariz',
    },
  },
];
