export const Texts = {
  spanish: {
    header: {
      title: 'Fullstack Developers',
      subtitle: 'Buscando trabajo de programadoras',
      welcome: 'Hola! Encantado de verte por aquí :)',
      description: [
        'Somos un grupo de estudiantes que acabamos de terminar un bootcamp intensivo de 5 meses.',
        'Hemos vivido un montón de cosas juntas - incluyendo 712 horas de clases, 2 hackathons, 2 proyectos en grupo y un proyecto final junto a un cliente real con el periódico La Vanguardia y el grupo de música La Pegatina -.',
        'Entonces pensamos: ¿Qué mejor forma para buscar trabajo que hacerlo todas juntas?',
        'Hemos creado esta página con este dominio para poder mostrar de forma más directa nuestros portfolios. Simplemente haz scroll hacia abajo y nos encontrarás... y nos conocerás! Ahí tienes acceso a nuestro Github, Linkedin, Redes Sociales, hemos escrito una pequeña bio... y hasta grabado un vídeo!',
        'Si estás buscando contratar a developers, hecha un vistazo y verás como hemos creado una solicón que te ayudará a encontrar quien puede encajar mejor en esa posición incluso antes de entrevistarnos :)',
        'Muchas gracias por visitarnos!',
      ],
      developerTitle: 'Conóce al equipo - Contracta talento',
      mentorTitle: 'Los mentores',
      from: 'de ',
      seeMore: 'Mira mi perfil',
    },
    profile: {
      from: 'De ',
      living: 'Viviendo en ',
      aboutMe: 'Sobre mí',
      watchMe: 'Mírame',
      myProjects: 'Mis proyectos',
      tech: 'tecnologías que uso:',
      checkIt: 'Míralo online ',
      here: 'aquí',
      developedWith: 'Programado con: ',
      ytNotReady: 'El vídeo no está disponible aún',
    },
  },
  english: {
    header: {
      title: 'Current Fullstack Developers',
      subtitle: 'Looking for tech jobs',
      welcome: 'Welcome! So lovely to see you :)',
      description: [
        'We\'re a group of classmates who just finished their Bootcamp, after 5 months of practicing.',
        'We lived so many things together- including 712 hs of Classes, 2 Hackathons, 1 personal Project each, 1 Group Project, and a final Clent Real Project for La Vanguardia or La Pegatina music band-.',
        'Then we thought: What a better way to look for work that doing it all together?',
        'So, we created this webpage -and selected this domain- to show our portfolios in a more pragmatic way. Just scroll down, and you\'ll find us... and who we are! You\'ll have access to our Github, our Linkedin, Social media, we even wrote a short bio and... recorded a video about ourselves!',
        'If you\'re looking to hire Developers, take a look, and you\'ll see how we produced a solution that we\'ll help you know who fits for the position even before interviewing us :)',
        'Thanks for visiting!',
      ],
      developerTitle: 'Meet our team - Hire real talents',
      mentorTitle: 'The mentors',
      from: 'from ',
      seeMore: 'Check my profile',
    },
    profile: {
      from: 'From ',
      living: 'Living in ',
      aboutMe: 'About me',
      watchMe: 'Watch me',
      myProjects: 'My projects',
      tech: 'technologies I use:',
      checkIt: 'Check it online ',
      here: 'here',
      developedWith: 'Developed with: ',
      ytNotReady: 'Video not ready yet',
    },
  },
};
